#!/usr/bin/env node

const fs = require('fs')
const testEvents = require('yaml/dist/test-events').default

const src = fs.readFileSync('/dev/stdin').toString()
const { events, error } = testEvents(src)
fs.writeSync(1, events.join('\n') + '\n')
if (error) {
  fs.writeSync(2, error.message)
  process.exit(1)
}
