#!/usr/bin/env node

const fs = require('fs')
const YAML = require('yaml').default

const src = fs.readFileSync('/dev/stdin').toString()
const docs = YAML.parseDocuments(src).map(doc => {
  if (doc.errors.length !== 0) throw doc.errors[0]
  return JSON.stringify(doc.toJSON(), null, 2) + '\n'
})
fs.writeSync(1, docs.join(''))
