#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use YAML::Syck;

$YAML::Syck::ImplicitUnicode = 1;
$YAML::Syck::ImplicitTyping = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

my $yaml = do { local $/; <> };
print Dumper Load $yaml;
