#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use Encode;
use YAML::Tiny;
use Mojo::JSON;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

print Mojo::JSON::encode_json( Load decode_utf8 do { local $/; <> } );
