#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use YAML::PP::Loader;
use JSON::XS;

my $coder = JSON::XS->new->ascii->pretty->allow_nonref->canonical;
my $yaml = do { local $/; <> };
my @docs = YAML::PP::Loader->new(boolean => 'JSON::PP')->load($yaml);
print $coder->encode($_) for @docs;
