#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use YAML::PP::Loader;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

my $yaml = do { local $/; <> };
my @docs = YAML::PP::Loader->new(boolean => 'perl')->load($yaml);
print Dumper @docs;
