#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use Encode;
use YAML::Tiny;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

print Dumper Load decode_utf8 do { local $/; <> };
