#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Encode;

use YAML::PP::Parser;
my $parser = YAML::PP::Parser->new(
  receiver => sub {
    my ($self, @args) = @_;
    my $event = YAML::PP::Parser->event_to_test_suite(\@args);
    $event = encode_utf8($event);
    say $event;
  },
);

my $yaml = decode_utf8 do { local $/; <> };
$parser->parse_string($yaml);
