#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use YAML::XS;
$YAML::XS::Boolean = 'JSON::PP';
$YAML::XS::LoadBlessed = 0;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

my $yaml = do { local $/; <> };
print Dumper YAML::XS::Load $yaml;
