#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Data::Dumper;
use Encode;
use YAML::PP;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Indent=2;
$Data::Dumper::Terse=1;

my $yaml = decode_utf8 do { local $/; <> };
my @docs = YAML::PP->new(boolean => 'perl')->load_string($yaml);
print Dumper @docs;
