#!/usr/bin/env python

import sys
import pprint
import yaml
import json

for doc in yaml.load_all(sys.stdin.read()):
    try:
        print json.dumps(doc, sort_keys=True, indent=2)
    except:
        print "Error json.dumps:", sys.exc_info()[0]
        raise
