#!/usr/bin/env python

import sys
import pprint
import yaml
import time

count = sys.argv[1]

filenames = sys.stdin.readlines()
filenames = [x.strip() for x in filenames]
content = []
for file in filenames:
    with open(file) as f:
        string = f.read()
        content.append([file, string])

start = time.time()

for i in range(0, int(count)):

    for item in content:
        string = item[1]
        for event in yaml.parse(string):
            next

end = time.time()
elapsed = (end - start) * 1000
print("%f" % elapsed)
