set switchbuf=useopen
set autoread exrc
map \o :rightbelow split .<CR>
map \O :rightbelow vsplit .<CR>
map <SPACE> :sb input.yaml<CR>:w<BAR>!timeout 5 yaml-editor RUN<CR><CR>
map \g :sb input.yaml<CR>:w<BAR>!timeout 5 yaml-editor RUN<CR><CR>:wa<BAR>!gist-paste *<CR>
nnoremap <leader>t :sb input.yaml<CR>:w<BAR>!timeout 5 yaml-editor RUN<CR><CR>:rightbelow vsplit `yaml-editor TESTML`<CR>:wincmd L<CR>
nnoremap <leader>s :sb input.yaml<CR>:w<BAR>!timeout 5 yaml-editor RUN<CR><CR>:rightbelow vsplit `yaml-editor SAVE`<CR>:wincmd L<CR>
map \c :sb input.yaml<CR><BAR>ggVGd
map \q :qa!<CR>
map \h :sb help<CR>:wincmd H<CR>

set et
set sw=2
set ts=2
set sts=2
set nosmartindent
set number

if exists("b:did_indent")
  finish
endif
"runtime! indent/ruby.vim
"unlet! b:did_indent
let b:did_indent = 1

let g:netrw_list_hide= '.*\.swp$,^.vimrc$,^\.\./$,^\./$,^help$,^TEST.tml$'
let g:netrw_banner=0

setlocal autoindent sw=2 et
setlocal indentexpr=GetYamlIndent()
setlocal indentkeys=o,O,*<Return>,!^F

function! GetYamlIndent()
  let lnum = v:lnum - 1
  if lnum == 0
    return 0
  endif
  let line = substitute(getline(lnum),'\s\+$','','')
  let indent = indent(lnum)
  let increase = indent + &sw
  if line =~ ':$'
    return increase
  else
    return indent
  endif
endfunction
